server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/skylink_auth
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: ThisIsMyVerySecretKeyForSkyLinkAuthentication2026ThisIsMyVerySecretKey
  expiration: 86400000